let a=2;
let b=4.1;
let c=0;
let d=true;
let e=false;
let firstName= "sarah";
let lastName="ahmed";
let greeting='ramzan mubarak';
let carNo = "AUP-708";
let chair=null;
let chair2;
 console.log( a );
 console.log( typeof b );
 console.log(c);
 console.log(typeof d);
 console.log(e);
 console.log(firstName);
 console.log(lastName);
 console.log( typeof greeting);
 console.log(chair);
 console.log(chair2);
